# Información de la aplicación 
info:
    app: 
        encoding: '@project.build.sourceEncoding@' 

        java: 
            source: '@java.version@'  
            target: '@java.version@' 

        version: '1.0.0'
        name: 'Crud'

Spring:
    application:
        name: 'Crud'
    main:
        banner-mode: 'CONSOLE'

    datasource:
        url: jdbc:mysql://localhost:3306/testdb
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa: 
        show-sql: true 
        open-in-view: false 
        hibernate:
            ddl-auto: update

    sql:
        init:
            mode: always
            platform: mysql
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql
    doc:
         swagger-ui:
         patch: /swagger-ui/index.html
         enable: true

    user:
        time-zone: 'UTC'

server:
   port: 8090
   compression:
        enabled: true


logging:
    config: classpath:log4j2.xml

